baseURL                       = "https://rohismaga.netlify.app/"
languageCode                  = "id"
title                         = "Rohismaga"
theme                         = "personal-site"
summaryLength                 = 10

[Author] # Used in authorbox
  name                        = "Rohis SMA Negeri 3 Semarang"
  bio                         = "Dikelola oleh Divisi Dakwah. Salah satu divisi yang ada di Rohis SMA Negeri 3 Semarang yang bertugas untuk mempublikasikan kegiatan dakwah Rohismaga. Bukan yang paling benar, apalagi tenar, cuma mau ngajak untuk sama-sama belajar"
  avatar                      = "img/logo-rohis.png"
  job                         = "Organisasi"
  gender                      = "male"
  email                       = "rohismaga17@gmail.com"
  donate                      = false
  
[Params]
  description                 = "Website Blog yang berisi informasi mengenai Rohis SMA Negeri 3 Semarang" # Site Description. Used in meta description
  images                      = ["img/logo-rohis.png"]
  copyright                   = "Rohismaga X IOT SMAGA" # Copyright holder, otherwise will use .Site.Title
  opengraph                   = true # Enable OpenGraph if true
  twitter_cards               = true # Enable Twitter Cards if true
  mainSections                = ["post"] # Set main page sections
  projectSections             = ["pengurus"] # Set main page sections
  dateFormat                  = "January 02, 2006" # Change the format of dates
  customCSS                 = ["css/custom.css"] # Include custom CSS files
  customJS                    = ["sw.js"]
  mainMenuAlignment           = "right" # Align main menu (desktop version) to the right side
  authorbox                   = true # Show authorbox at bottom of single pages if true
  comments                    = true # Enable comments for all site pages
  related                     = true # Enable Related content for single pages
  relatedMax                  = 5
  mathjax                     = false # Enable MathJax for all site pages
  hideNoPostsWarning          = false # Don't show no posts empty state warning in main page, if true
  fontUnit                    = "em"
  largestFontSize             = 2.5
  smallestFontSize            = 1
  paginateLength              = 5
  googleSearchConsole         = "" # Google search console code
  GoogleAnalytics             = "" # Google analisi code
  fb_admins                   = "" # Your facebook admin
  fb_app_id                   = "" # Your facebook app id
  customSearchId              = "004021659876411083349:a2ysxpichpc"
  endMessagePost              = "Semoga artikel ini bermanfaat. Jika terdapat kesalahan penulisan, typo, ataupun juga kurang sesuai dalam penulisan, bantu Saya"
  editContentPageLink         = "https://github.com/iotsmaga/rohismaga-blog/edit/main/content/"
  formspreeId                 = "mzbkwbkb"
  subTitle                    = "| Organisasi Islam di SMA Negeri 3 Semarang"

[Params.Hero]
  title                       = "🕌 ROHISMAGA"
  desc                        = "Official Website Rohis SMA Negeri 3 Semarang"

[Params.Entry]
  meta                        = ["date", "categories"] # Enable meta fields in given order
  toc                         = true # Enable Table of Contents
  tocOpen                     = false # Open Table of Contents block. Optional

[Params.Featured]
  previewOnly                 = false # Show only preview featured image

[Params.Comments]
  repository                  = "iotsmaga/rohismaga-blog"

# Navigation bar
[menu]

[[menu.main]]
identifier = "Artikel"
pre = "📝"
url = "/post" 
weight = 1 

[[menu.main]]
identifier = "Proker"
pre = "📅"
url = "/events" 
weight = 2 

[[menu.main]]
identifier = "Pengurus"
pre = "⭐"
url = "/pengurus" 
weight = 3 

[[menu.main]]
identifier = "About"
pre = "😃"
url = "/about" 
weight = 4

[[menu.main]]
identifier = "Kontak"
pre = "📞"
url = "/contacts" 
weight = 5

[Params.Breadcrumb]
  enable                      = true # Enable breadcrumb block globally
  homeText                    = "Home" # Home node text

[Params.Social]
  facebook                    = ""
  instagram                   = "rohismaga"
 

[Params.Share] # Entry Share block
  facebook                    = true
  instagram                   = true
 
# Web App Manifest settings
# https://www.w3.org/TR/appmanifest/
# https://developers.google.com/web/fundamentals/web-app-manifest/
[Params.Manifest]
  name                        = "Rohis SMA Negeri 3 Semarang"
  shortName                   = "Rohismaga"
  display                     = "standalone"
  startUrl                    = "/?utm_source=homescreen"
  backgroundColor             = "#8dc153"
  themeColor                  = "#27ae60"
  description                 = "Personal Site By IOT SMAGA"
  orientation                 = "portrait"
  scope                       = "/"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType                 = "application/json"
    baseName                  = "manifest"
    isPlainText               = true
    notAlternative            = true

[taxonomies]
    category = "categories"
    series = "series"
    tags = "tags"
    
[outputs]
  home                        = ["HTML", "RSS", "MANIFEST"]

enableRobotsTXT               = true

# Pagination
Paginate                      = 5
 
[sitemap]
  changefreq = "daily"
  changeFreqPage = "monthly"
  filename = "sitemap.xml"
  priority = 1
  priorityPage = 0.5

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10

# Code
[markup]
  # defaultMarkdownHandler    = "blackfriday"
  # [markup.goldmark]
  [markup.highlight]
    codeFences                = true
    guessSyntax               = false
    hl_Lines                  = ""
    lineNoStart               = 1
    lineNos                   = true
    lineNumbersInTable        = true
    noClasses                 = false
    style                     = "dracula"
    tabWidth                  = 4
  [markup.tableOfContents]
    endLevel                  = 3
    ordered                   = false
    startLevel                = 2
